image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375

stages:
  - test
  - build
  - deploy

test:
  image: node:10.15.0-alpine
  stage: test
  before_script:
    - npm install -g gatsby-cli
    - npm install
  script:
    - gatsby build
  artifacts:
    paths:
      - publish
    expire_in: 1 day

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - tags
  except:
    - branches

deploy:
  image: lwolf/kubectl_deployer:latest
  stage: deploy
  script:
    - sed -i "s/IMAGE_TAG/"${CI_COMMIT_TAG}"/g" deployment.yml
    - kubectl --namespace=${KUBE_NAMESPACE} apply -f deployment.yml
  only:
    - tags
  except:
    - branches
