apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: nginx
        image: registry.pkg.github.com/thepiconerd/lynxlanding
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry
---
kind: Service
apiVersion: v1
metadata:
  name: landing
  labels:
    app: landing
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: landing
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: landing-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - lynx.agency
    secretName: landing-ingress-cert
  rules:
  - host: lynx.agency
    http:
      paths:
      - backend:
          serviceName: landing
          servicePort: 80